platform :ios, '8.0'
use_frameworks!

target 'KidsTC' do
    
    pod 'UMengAnalytics',               '~> 4.1.0'
    pod 'GTSDK',                        '~> 1.5.0'
    pod 'BaiduMapKit',                  '~> 3.0.0'
    pod 'WeiboSDK',                     '~> 3.1.3'
    pod 'Bugly',                        '~> 2.4.6'
    
    pod 'AFNetworking',                 '~> 3.1.0'
    pod 'SDWebImage',                   '~> 3.8.2'
    pod 'MJRefresh',                    '~> 3.1.12'
    pod 'YYKit',                        '~> 1.0.9'
    pod 'SSZipArchive',                 '~> 1.6.1'
    pod 'KMNavigationBarTransition',    '~> 0.0.10'
    pod 'SVProgressHUD',                '~> 2.1.2'
    pod 'Masonry',                      '~> 1.0.2'
    pod 'NJKWebViewProgress',           '~> 0.2.3'
    pod 'Colours',                      '~> 5.13.0'
    pod 'TZImagePickerController',      '~> 1.7.8'
    pod 'SAMKeychain',                  '~> 1.5.2'
    pod 'FSCalendar',                   '~> 2.6.0'
    pod 'PLPlayerKit',                  '~> 2.4.0'
    pod 'FMDB',                         '~> 2.6.2'
    pod 'JSPatchPlatform',              '~> 1.6.2'
    pod 'JSPatchPlatform/Extensions'
    pod 'JSPatchPlatform/JPCFunction'
    pod 'JSPatchPlatform/JPCFunctionBinder'
    
end
